=== yevkk/OOPISS3/Lab2/src/main/resources/Tariff.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="urn:Lab.Namespace"
            xmlns:lab="urn:Lab.Namespace"
            elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.w3c.org/2001/XMLSchema ">
    <xsd:element name="tariffs">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="tariff" type="lab:Tariff" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Tariff">
        <xsd:sequence>
            <xsd:element name="payroll">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="0"/>
                        <xsd:maxInclusive value="500"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="callPrice" minOccurs="3" maxOccurs="3">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="0"/>
                        <xsd:maxInclusive value="10"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="smsPrice">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="0"/>
                        <xsd:maxInclusive value="5"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="tariffParameters" type="lab:TariffParameters"/>
        </xsd:sequence>
        <xsd:attribute name="name" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:ID"/>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="operatorName" type="xsd:string" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="TariffParameters">
        <xsd:sequence>
            <xsd:element name="favNumber">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[0]\d{9}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="tariffication">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="12sec"/>
                        <xsd:enumeration value="min"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="joinPrice">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="0"/>
                        <xsd:maxInclusive value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== yevkk/OOPISS3/Lab2/src/main/resources/tariffs.xml
<?xml version="1.0" encoding="UTF-8"?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Tariff.xsd">
    <tariff name="S" operatorName="Vodafone">
        <payroll>85</payroll>
        <callPrice>1</callPrice>
        <callPrice>2</callPrice>
        <callPrice>5</callPrice>
        <smsPrice>1</smsPrice>
        <tariffParameters>
            <favNumber>0778881122</favNumber>
            <tariffication>min</tariffication>
            <joinPrice>50</joinPrice>
        </tariffParameters>
    </tariff>
    <tariff name="L" operatorName="Vodafone">
        <payroll>150</payroll>
        <callPrice>0</callPrice>
        <callPrice>1</callPrice>
        <callPrice>4</callPrice>
        <smsPrice>2</smsPrice>
        <tariffParameters>
            <favNumber>0991114433</favNumber>
            <tariffication>min</tariffication>
            <joinPrice>75</joinPrice>
        </tariffParameters>
    </tariff>
</tariffs>

=== yevkk/OOPISS3/Lab2/src/test/resources/singleTariffs.xml
<?xml version="1.0" encoding="UTF-8"?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="urn:Lab.Namespace"
         xsi:schemaLocation="urn:Lab.Namespace Tariff.xsd">
    <tariff name="L" operatorName="O2">
        <payroll>150</payroll>
        <callPrice>0</callPrice>
        <callPrice>1</callPrice>
        <callPrice>4</callPrice>
        <smsPrice>2</smsPrice>
        <tariffParameters>
            <favNumber>0991114433</favNumber>
            <tariffication>min</tariffication>
            <joinPrice>75</joinPrice>
        </tariffParameters>
    </tariff>
</tariffs>

=== yevkk/OOPISS3/Lab2/src/test/resources/someTariffs.xml
<?xml version="1.0" encoding="UTF-8"?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="urn:Lab.Namespace"
         xsi:schemaLocation="urn:Lab.Namespace Tariff.xsd">
    <tariff name="S" operatorName="O2">
        <payroll>85</payroll>
        <callPrice>1</callPrice>
        <callPrice>2</callPrice>
        <callPrice>5</callPrice>
        <smsPrice>1</smsPrice>
        <tariffParameters>
            <favNumber>0778881122</favNumber>
            <tariffication>min</tariffication>
            <joinPrice>50</joinPrice>
        </tariffParameters>
    </tariff>
    <tariff name="L" operatorName="O2">
        <payroll>150</payroll>
        <callPrice>0</callPrice>
        <callPrice>1</callPrice>
        <callPrice>4</callPrice>
        <smsPrice>2</smsPrice>
        <tariffParameters>
            <favNumber>0991114433</favNumber>
            <tariffication>min</tariffication>
            <joinPrice>75</joinPrice>
        </tariffParameters>
    </tariff>
    <tariff name="Plush" operatorName="Plus">
        <payroll>50</payroll>
        <callPrice>1</callPrice>
        <callPrice>2</callPrice>
        <callPrice>2</callPrice>
        <smsPrice>1</smsPrice>
        <tariffParameters>
            <favNumber>0331231212</favNumber>
            <tariffication>12sec</tariffication>
            <joinPrice>15</joinPrice>
        </tariffParameters>
    </tariff>
</tariffs>
